version: '3.1'

services:
  proxy:
    image: nginx:1.25.4-alpine
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend
      - backend

  server1:
    image: nginx:1.25.4-alpine
    container_name: server1
    # if this is uncommented, the app1/index.html will be served on the frontend
    # ports:
    #   - 8081:80
    volumes:
      - ./app1/index.html:/usr/share/nginx/html/index.html
    networks:
      - backend

  server2:
    image: nginx:1.25.4-alpine
    container_name: server2
    # ports:
    #   - 8082:80
    volumes:
      - ./app2/index.html:/usr/share/nginx/html/index.html
    networks:
      - backend

networks:
  frontend:
  backend:
